plugins {
    id 'application'
    id("com.gradleup.shadow") version "9.3.0"
}

application {
    mainClass = 'org.education.Main'
}

dependencies {
    implementation(project(':module1'))
}

subprojects {
    apply plugin: 'java'

    group = 'org.education'
    version = '1.0.0'

    repositories {
        mavenCentral()
    }

    dependencies {
        testImplementation platform('org.junit:junit-bom:5.10.0')
        testImplementation 'org.junit.jupiter:junit-jupiter'
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    }

    java {
        sourceCompatibility = JavaVersion.VERSION_17
    }

    test {
        useJUnitPlatform()
    }
}

tasks.register('info') {
    doLast {
        println "Java: ${System.getProperty('java.version')}"
        println "Gradle: ${gradle.gradleVersion}"
    }
}

tasks.register('greeting') {
    doLast {
        println("Hello user!")
    }
}

info.dependsOn(greeting)
