plugins {
    alias(libs.plugins.app) // https://docs.gradle.org/current/userguide/application_plugin.html
    alias(libs.plugins.shadow) // https://plugins.gradle.org/plugin/com.gradleup.shadow
    alias(libs.plugins.slack)
}

application {
    mainClass = 'org.education.Main'
}

dependencies {
    implementation(projects.module1)
}

tasks.register('info') {
    doLast {
        println "Java: ${System.getProperty('java.version')}"
        println "Gradle: ${gradle.gradleVersion}"
    }
}

slack {
    token = System.getenv("SLACK_TOKEN")
    channel = System.getenv("SLACK_CHANNEL")
    message = "Build is running"
}

run.dependsOn(sendSlackMessage)
