plugins {
    alias(libs.plugins.java.gradle)
    alias(libs.plugins.groovy)
    alias(libs.plugins.groovy.gradle)
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(libs.slack)
    implementation(libs.groovy)
}

gradlePlugin {
    plugins {
        slackNotification {
            id = 'org.education.slack-notification'
            implementationClass = 'org.education.slack.SlackPlugin'
        }
    }
}